sudo: required
services:
  - docker
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - ROS_PARALLEL_TEST_JOBS="-j1"
    - CATKIN_PARALLEL_TEST_JOBS="-j1"
  matrix:
    - ROS_DISTRO=hydro USE_DEB=true ROS_PARALLEL_JOBS="-j2 -l2"
#    - ROS_DISTRO=hydro USE_DEB=false ROS_PARALLEL_JOBS="-j2 -l2" NOT_TEST_INSTALL="true"
    - ROS_DISTRO=indigo USE_DEB=true ROS_PARALLEL_JOBS="-j8"
#    - ROS_DISTRO=indigo USE_DEB=false ROS_PARALLEL_JOBS="-j8" NOT_TEST_INSTALL="true"
    - ROS_DISTRO=jade USE_DEB=true ROS_PARALLEL_JOBS="-j8"
#    - ROS_DISTRO=jade USE_DEB=false ROS_PARALLEL_JOBS="-j8" NOT_TEST_INSTALL="true"
before_install:
  - docker build -t jsk/ros:indigo .travis
before_script:
  # style check
  - sudo pip install flake8 hacking
  - flake8 jsk_data/src/jsk_data
script: source .travis/travis.sh
